<?php
/**
 * Children
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nomad
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nomad\Model;

use \ArrayAccess;
/**
 * Children Class Doc Comment
 *
 * @category    Class
 * @description Model for Children
 * @package     Nomad
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Children implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'dead' => 'int',
        'pending' => 'int',
        'running' => 'int'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'dead' => 'Dead',
        'pending' => 'Pending',
        'running' => 'Running'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'dead' => 'setDead',
        'pending' => 'setPending',
        'running' => 'setRunning'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'dead' => 'getDead',
        'pending' => 'getPending',
        'running' => 'getRunning'
    );
  
    
    /**
      * $dead 
      * @var int
      */
    protected $dead;
    
    /**
      * $pending 
      * @var int
      */
    protected $pending;
    
    /**
      * $running 
      * @var int
      */
    protected $running;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->dead = $data["dead"];
            $this->pending = $data["pending"];
            $this->running = $data["running"];
        }
    }
    
    /**
     * Gets dead
     * @return int
     */
    public function getDead()
    {
        return $this->dead;
    }
  
    /**
     * Sets dead
     * @param int $dead 
     * @return $this
     */
    public function setDead($dead)
    {
        
        $this->dead = $dead;
        return $this;
    }
    
    /**
     * Gets pending
     * @return int
     */
    public function getPending()
    {
        return $this->pending;
    }
  
    /**
     * Sets pending
     * @param int $pending 
     * @return $this
     */
    public function setPending($pending)
    {
        
        $this->pending = $pending;
        return $this;
    }
    
    /**
     * Gets running
     * @return int
     */
    public function getRunning()
    {
        return $this->running;
    }
  
    /**
     * Sets running
     * @param int $running 
     * @return $this
     */
    public function setRunning($running)
    {
        
        $this->running = $running;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Nomad\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Nomad\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
