<?php
/**
 * Constraint
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nomad
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nomad\Model;

use \ArrayAccess;
/**
 * Constraint Class Doc Comment
 *
 * @category    Class
 * @description Model for Constraints
 * @package     Nomad
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Constraint implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'l_target' => 'string',
        'operand' => 'string',
        'r_target' => 'string'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'l_target' => 'LTarget',
        'operand' => 'Operand',
        'r_target' => 'RTarget'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'l_target' => 'setLTarget',
        'operand' => 'setOperand',
        'r_target' => 'setRTarget'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'l_target' => 'getLTarget',
        'operand' => 'getOperand',
        'r_target' => 'getRTarget'
    );
  
    
    /**
      * $l_target 
      * @var string
      */
    protected $l_target;
    
    /**
      * $operand 
      * @var string
      */
    protected $operand;
    
    /**
      * $r_target 
      * @var string
      */
    protected $r_target;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->l_target = $data["l_target"];
            $this->operand = $data["operand"];
            $this->r_target = $data["r_target"];
        }
    }
    
    /**
     * Gets l_target
     * @return string
     */
    public function getLTarget()
    {
        return $this->l_target;
    }
  
    /**
     * Sets l_target
     * @param string $l_target 
     * @return $this
     */
    public function setLTarget($l_target)
    {
        
        $this->l_target = $l_target;
        return $this;
    }
    
    /**
     * Gets operand
     * @return string
     */
    public function getOperand()
    {
        return $this->operand;
    }
  
    /**
     * Sets operand
     * @param string $operand 
     * @return $this
     */
    public function setOperand($operand)
    {
        $allowed_values = array("regexp", "set_contains", "distinct_host", "distinct_property", "=", "==", "is", "!=", "not", ">", ">=", "<", "<=");
        if (!in_array($operand, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'operand', must be one of 'regexp', 'set_contains', 'distinct_host', 'distinct_property', '=', '==', 'is', '!=', 'not', '>', '>=', '<', '<='");
        }
        $this->operand = $operand;
        return $this;
    }
    
    /**
     * Gets r_target
     * @return string
     */
    public function getRTarget()
    {
        return $this->r_target;
    }
  
    /**
     * Sets r_target
     * @param string $r_target 
     * @return $this
     */
    public function setRTarget($r_target)
    {
        
        $this->r_target = $r_target;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Nomad\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Nomad\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
