<?php
/**
 * GetJobAllocationsResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nomad
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nomad\Model;

use \ArrayAccess;
/**
 * GetJobAllocationsResponse Class Doc Comment
 *
 * @category    Class
 * @description Model for GetJobAllocationsResponse
 * @package     Nomad
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetJobAllocationsResponse implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'client_description' => 'string',
        'client_status' => 'string',
        'create_index' => 'int',
        'desired_description' => 'string',
        'desired_status' => 'string',
        'eval_id' => 'string',
        'id' => 'string',
        'job_id' => 'string',
        'modify_index' => 'int',
        'name' => 'string',
        'node_id' => 'string',
        'task_group' => 'string'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'client_description' => 'ClientDescription',
        'client_status' => 'ClientStatus',
        'create_index' => 'CreateIndex',
        'desired_description' => 'DesiredDescription',
        'desired_status' => 'DesiredStatus',
        'eval_id' => 'EvalID',
        'id' => 'ID',
        'job_id' => 'JobID',
        'modify_index' => 'ModifyIndex',
        'name' => 'Name',
        'node_id' => 'NodeID',
        'task_group' => 'TaskGroup'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'client_description' => 'setClientDescription',
        'client_status' => 'setClientStatus',
        'create_index' => 'setCreateIndex',
        'desired_description' => 'setDesiredDescription',
        'desired_status' => 'setDesiredStatus',
        'eval_id' => 'setEvalId',
        'id' => 'setId',
        'job_id' => 'setJobId',
        'modify_index' => 'setModifyIndex',
        'name' => 'setName',
        'node_id' => 'setNodeId',
        'task_group' => 'setTaskGroup'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'client_description' => 'getClientDescription',
        'client_status' => 'getClientStatus',
        'create_index' => 'getCreateIndex',
        'desired_description' => 'getDesiredDescription',
        'desired_status' => 'getDesiredStatus',
        'eval_id' => 'getEvalId',
        'id' => 'getId',
        'job_id' => 'getJobId',
        'modify_index' => 'getModifyIndex',
        'name' => 'getName',
        'node_id' => 'getNodeId',
        'task_group' => 'getTaskGroup'
    );
  
    
    /**
      * $client_description 
      * @var string
      */
    protected $client_description;
    
    /**
      * $client_status 
      * @var string
      */
    protected $client_status;
    
    /**
      * $create_index 
      * @var int
      */
    protected $create_index;
    
    /**
      * $desired_description 
      * @var string
      */
    protected $desired_description;
    
    /**
      * $desired_status 
      * @var string
      */
    protected $desired_status;
    
    /**
      * $eval_id 
      * @var string
      */
    protected $eval_id;
    
    /**
      * $id 
      * @var string
      */
    protected $id;
    
    /**
      * $job_id 
      * @var string
      */
    protected $job_id;
    
    /**
      * $modify_index 
      * @var int
      */
    protected $modify_index;
    
    /**
      * $name 
      * @var string
      */
    protected $name;
    
    /**
      * $node_id 
      * @var string
      */
    protected $node_id;
    
    /**
      * $task_group 
      * @var string
      */
    protected $task_group;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->client_description = $data["client_description"];
            $this->client_status = $data["client_status"];
            $this->create_index = $data["create_index"];
            $this->desired_description = $data["desired_description"];
            $this->desired_status = $data["desired_status"];
            $this->eval_id = $data["eval_id"];
            $this->id = $data["id"];
            $this->job_id = $data["job_id"];
            $this->modify_index = $data["modify_index"];
            $this->name = $data["name"];
            $this->node_id = $data["node_id"];
            $this->task_group = $data["task_group"];
        }
    }
    
    /**
     * Gets client_description
     * @return string
     */
    public function getClientDescription()
    {
        return $this->client_description;
    }
  
    /**
     * Sets client_description
     * @param string $client_description 
     * @return $this
     */
    public function setClientDescription($client_description)
    {
        
        $this->client_description = $client_description;
        return $this;
    }
    
    /**
     * Gets client_status
     * @return string
     */
    public function getClientStatus()
    {
        return $this->client_status;
    }
  
    /**
     * Sets client_status
     * @param string $client_status 
     * @return $this
     */
    public function setClientStatus($client_status)
    {
        
        $this->client_status = $client_status;
        return $this;
    }
    
    /**
     * Gets create_index
     * @return int
     */
    public function getCreateIndex()
    {
        return $this->create_index;
    }
  
    /**
     * Sets create_index
     * @param int $create_index 
     * @return $this
     */
    public function setCreateIndex($create_index)
    {
        
        $this->create_index = $create_index;
        return $this;
    }
    
    /**
     * Gets desired_description
     * @return string
     */
    public function getDesiredDescription()
    {
        return $this->desired_description;
    }
  
    /**
     * Sets desired_description
     * @param string $desired_description 
     * @return $this
     */
    public function setDesiredDescription($desired_description)
    {
        
        $this->desired_description = $desired_description;
        return $this;
    }
    
    /**
     * Gets desired_status
     * @return string
     */
    public function getDesiredStatus()
    {
        return $this->desired_status;
    }
  
    /**
     * Sets desired_status
     * @param string $desired_status 
     * @return $this
     */
    public function setDesiredStatus($desired_status)
    {
        
        $this->desired_status = $desired_status;
        return $this;
    }
    
    /**
     * Gets eval_id
     * @return string
     */
    public function getEvalId()
    {
        return $this->eval_id;
    }
  
    /**
     * Sets eval_id
     * @param string $eval_id 
     * @return $this
     */
    public function setEvalId($eval_id)
    {
        
        $this->eval_id = $eval_id;
        return $this;
    }
    
    /**
     * Gets id
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }
  
    /**
     * Sets id
     * @param string $id 
     * @return $this
     */
    public function setId($id)
    {
        
        $this->id = $id;
        return $this;
    }
    
    /**
     * Gets job_id
     * @return string
     */
    public function getJobId()
    {
        return $this->job_id;
    }
  
    /**
     * Sets job_id
     * @param string $job_id 
     * @return $this
     */
    public function setJobId($job_id)
    {
        
        $this->job_id = $job_id;
        return $this;
    }
    
    /**
     * Gets modify_index
     * @return int
     */
    public function getModifyIndex()
    {
        return $this->modify_index;
    }
  
    /**
     * Sets modify_index
     * @param int $modify_index 
     * @return $this
     */
    public function setModifyIndex($modify_index)
    {
        
        $this->modify_index = $modify_index;
        return $this;
    }
    
    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }
  
    /**
     * Sets name
     * @param string $name 
     * @return $this
     */
    public function setName($name)
    {
        
        $this->name = $name;
        return $this;
    }
    
    /**
     * Gets node_id
     * @return string
     */
    public function getNodeId()
    {
        return $this->node_id;
    }
  
    /**
     * Sets node_id
     * @param string $node_id 
     * @return $this
     */
    public function setNodeId($node_id)
    {
        
        $this->node_id = $node_id;
        return $this;
    }
    
    /**
     * Gets task_group
     * @return string
     */
    public function getTaskGroup()
    {
        return $this->task_group;
    }
  
    /**
     * Sets task_group
     * @param string $task_group 
     * @return $this
     */
    public function setTaskGroup($task_group)
    {
        
        $this->task_group = $task_group;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Nomad\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Nomad\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
