<?php
/**
 * GetJobEvaluationsResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nomad
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nomad\Model;

use \ArrayAccess;
/**
 * GetJobEvaluationsResponse Class Doc Comment
 *
 * @category    Class
 * @description Model for GetJobEvaluationsResponse
 * @package     Nomad
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetJobEvaluationsResponse implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'create_index' => 'int',
        'id' => 'string',
        'job_id' => 'string',
        'job_modify_index' => 'int',
        'modify_index' => 'int',
        'next_eval' => 'string',
        'node_id' => 'string',
        'node_modify_index' => 'int',
        'previous_eval' => 'string',
        'priority' => 'int',
        'status' => 'string',
        'status_description' => 'string',
        'triggered_by' => 'string',
        'type' => 'string',
        'wait' => 'int'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'create_index' => 'CreateIndex',
        'id' => 'ID',
        'job_id' => 'JobID',
        'job_modify_index' => 'JobModifyIndex',
        'modify_index' => 'ModifyIndex',
        'next_eval' => 'NextEval',
        'node_id' => 'NodeID',
        'node_modify_index' => 'NodeModifyIndex',
        'previous_eval' => 'PreviousEval',
        'priority' => 'Priority',
        'status' => 'Status',
        'status_description' => 'StatusDescription',
        'triggered_by' => 'TriggeredBy',
        'type' => 'Type',
        'wait' => 'Wait'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'create_index' => 'setCreateIndex',
        'id' => 'setId',
        'job_id' => 'setJobId',
        'job_modify_index' => 'setJobModifyIndex',
        'modify_index' => 'setModifyIndex',
        'next_eval' => 'setNextEval',
        'node_id' => 'setNodeId',
        'node_modify_index' => 'setNodeModifyIndex',
        'previous_eval' => 'setPreviousEval',
        'priority' => 'setPriority',
        'status' => 'setStatus',
        'status_description' => 'setStatusDescription',
        'triggered_by' => 'setTriggeredBy',
        'type' => 'setType',
        'wait' => 'setWait'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'create_index' => 'getCreateIndex',
        'id' => 'getId',
        'job_id' => 'getJobId',
        'job_modify_index' => 'getJobModifyIndex',
        'modify_index' => 'getModifyIndex',
        'next_eval' => 'getNextEval',
        'node_id' => 'getNodeId',
        'node_modify_index' => 'getNodeModifyIndex',
        'previous_eval' => 'getPreviousEval',
        'priority' => 'getPriority',
        'status' => 'getStatus',
        'status_description' => 'getStatusDescription',
        'triggered_by' => 'getTriggeredBy',
        'type' => 'getType',
        'wait' => 'getWait'
    );
  
    
    /**
      * $create_index 
      * @var int
      */
    protected $create_index;
    
    /**
      * $id 
      * @var string
      */
    protected $id;
    
    /**
      * $job_id 
      * @var string
      */
    protected $job_id;
    
    /**
      * $job_modify_index 
      * @var int
      */
    protected $job_modify_index;
    
    /**
      * $modify_index 
      * @var int
      */
    protected $modify_index;
    
    /**
      * $next_eval 
      * @var string
      */
    protected $next_eval;
    
    /**
      * $node_id 
      * @var string
      */
    protected $node_id;
    
    /**
      * $node_modify_index 
      * @var int
      */
    protected $node_modify_index;
    
    /**
      * $previous_eval 
      * @var string
      */
    protected $previous_eval;
    
    /**
      * $priority 
      * @var int
      */
    protected $priority;
    
    /**
      * $status 
      * @var string
      */
    protected $status;
    
    /**
      * $status_description 
      * @var string
      */
    protected $status_description;
    
    /**
      * $triggered_by 
      * @var string
      */
    protected $triggered_by;
    
    /**
      * $type 
      * @var string
      */
    protected $type;
    
    /**
      * $wait 
      * @var int
      */
    protected $wait;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->create_index = $data["create_index"];
            $this->id = $data["id"];
            $this->job_id = $data["job_id"];
            $this->job_modify_index = $data["job_modify_index"];
            $this->modify_index = $data["modify_index"];
            $this->next_eval = $data["next_eval"];
            $this->node_id = $data["node_id"];
            $this->node_modify_index = $data["node_modify_index"];
            $this->previous_eval = $data["previous_eval"];
            $this->priority = $data["priority"];
            $this->status = $data["status"];
            $this->status_description = $data["status_description"];
            $this->triggered_by = $data["triggered_by"];
            $this->type = $data["type"];
            $this->wait = $data["wait"];
        }
    }
    
    /**
     * Gets create_index
     * @return int
     */
    public function getCreateIndex()
    {
        return $this->create_index;
    }
  
    /**
     * Sets create_index
     * @param int $create_index 
     * @return $this
     */
    public function setCreateIndex($create_index)
    {
        
        $this->create_index = $create_index;
        return $this;
    }
    
    /**
     * Gets id
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }
  
    /**
     * Sets id
     * @param string $id 
     * @return $this
     */
    public function setId($id)
    {
        
        $this->id = $id;
        return $this;
    }
    
    /**
     * Gets job_id
     * @return string
     */
    public function getJobId()
    {
        return $this->job_id;
    }
  
    /**
     * Sets job_id
     * @param string $job_id 
     * @return $this
     */
    public function setJobId($job_id)
    {
        
        $this->job_id = $job_id;
        return $this;
    }
    
    /**
     * Gets job_modify_index
     * @return int
     */
    public function getJobModifyIndex()
    {
        return $this->job_modify_index;
    }
  
    /**
     * Sets job_modify_index
     * @param int $job_modify_index 
     * @return $this
     */
    public function setJobModifyIndex($job_modify_index)
    {
        
        $this->job_modify_index = $job_modify_index;
        return $this;
    }
    
    /**
     * Gets modify_index
     * @return int
     */
    public function getModifyIndex()
    {
        return $this->modify_index;
    }
  
    /**
     * Sets modify_index
     * @param int $modify_index 
     * @return $this
     */
    public function setModifyIndex($modify_index)
    {
        
        $this->modify_index = $modify_index;
        return $this;
    }
    
    /**
     * Gets next_eval
     * @return string
     */
    public function getNextEval()
    {
        return $this->next_eval;
    }
  
    /**
     * Sets next_eval
     * @param string $next_eval 
     * @return $this
     */
    public function setNextEval($next_eval)
    {
        
        $this->next_eval = $next_eval;
        return $this;
    }
    
    /**
     * Gets node_id
     * @return string
     */
    public function getNodeId()
    {
        return $this->node_id;
    }
  
    /**
     * Sets node_id
     * @param string $node_id 
     * @return $this
     */
    public function setNodeId($node_id)
    {
        
        $this->node_id = $node_id;
        return $this;
    }
    
    /**
     * Gets node_modify_index
     * @return int
     */
    public function getNodeModifyIndex()
    {
        return $this->node_modify_index;
    }
  
    /**
     * Sets node_modify_index
     * @param int $node_modify_index 
     * @return $this
     */
    public function setNodeModifyIndex($node_modify_index)
    {
        
        $this->node_modify_index = $node_modify_index;
        return $this;
    }
    
    /**
     * Gets previous_eval
     * @return string
     */
    public function getPreviousEval()
    {
        return $this->previous_eval;
    }
  
    /**
     * Sets previous_eval
     * @param string $previous_eval 
     * @return $this
     */
    public function setPreviousEval($previous_eval)
    {
        
        $this->previous_eval = $previous_eval;
        return $this;
    }
    
    /**
     * Gets priority
     * @return int
     */
    public function getPriority()
    {
        return $this->priority;
    }
  
    /**
     * Sets priority
     * @param int $priority 
     * @return $this
     */
    public function setPriority($priority)
    {
        
        $this->priority = $priority;
        return $this;
    }
    
    /**
     * Gets status
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }
  
    /**
     * Sets status
     * @param string $status 
     * @return $this
     */
    public function setStatus($status)
    {
        
        $this->status = $status;
        return $this;
    }
    
    /**
     * Gets status_description
     * @return string
     */
    public function getStatusDescription()
    {
        return $this->status_description;
    }
  
    /**
     * Sets status_description
     * @param string $status_description 
     * @return $this
     */
    public function setStatusDescription($status_description)
    {
        
        $this->status_description = $status_description;
        return $this;
    }
    
    /**
     * Gets triggered_by
     * @return string
     */
    public function getTriggeredBy()
    {
        return $this->triggered_by;
    }
  
    /**
     * Sets triggered_by
     * @param string $triggered_by 
     * @return $this
     */
    public function setTriggeredBy($triggered_by)
    {
        
        $this->triggered_by = $triggered_by;
        return $this;
    }
    
    /**
     * Gets type
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }
  
    /**
     * Sets type
     * @param string $type 
     * @return $this
     */
    public function setType($type)
    {
        
        $this->type = $type;
        return $this;
    }
    
    /**
     * Gets wait
     * @return int
     */
    public function getWait()
    {
        return $this->wait;
    }
  
    /**
     * Sets wait
     * @param int $wait 
     * @return $this
     */
    public function setWait($wait)
    {
        
        $this->wait = $wait;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Nomad\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Nomad\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
