<?php
/**
 * Jobs
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nomad
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nomad\Model;

use \ArrayAccess;
/**
 * Jobs Class Doc Comment
 *
 * @category    Class
 * @description Model for Jobs
 * @package     Nomad
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Jobs implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'create_index' => 'int',
        'id' => 'string',
        'modify_index' => 'int',
        'name' => 'string',
        'priority' => 'int',
        'status' => 'string',
        'status_description' => 'string',
        'type' => 'string'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'create_index' => 'CreateIndex',
        'id' => 'ID',
        'modify_index' => 'ModifyIndex',
        'name' => 'Name',
        'priority' => 'Priority',
        'status' => 'Status',
        'status_description' => 'StatusDescription',
        'type' => 'Type'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'create_index' => 'setCreateIndex',
        'id' => 'setId',
        'modify_index' => 'setModifyIndex',
        'name' => 'setName',
        'priority' => 'setPriority',
        'status' => 'setStatus',
        'status_description' => 'setStatusDescription',
        'type' => 'setType'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'create_index' => 'getCreateIndex',
        'id' => 'getId',
        'modify_index' => 'getModifyIndex',
        'name' => 'getName',
        'priority' => 'getPriority',
        'status' => 'getStatus',
        'status_description' => 'getStatusDescription',
        'type' => 'getType'
    );
  
    
    /**
      * $create_index 
      * @var int
      */
    protected $create_index;
    
    /**
      * $id 
      * @var string
      */
    protected $id;
    
    /**
      * $modify_index 
      * @var int
      */
    protected $modify_index;
    
    /**
      * $name 
      * @var string
      */
    protected $name;
    
    /**
      * $priority 
      * @var int
      */
    protected $priority;
    
    /**
      * $status 
      * @var string
      */
    protected $status;
    
    /**
      * $status_description 
      * @var string
      */
    protected $status_description;
    
    /**
      * $type 
      * @var string
      */
    protected $type;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->create_index = $data["create_index"];
            $this->id = $data["id"];
            $this->modify_index = $data["modify_index"];
            $this->name = $data["name"];
            $this->priority = $data["priority"];
            $this->status = $data["status"];
            $this->status_description = $data["status_description"];
            $this->type = $data["type"];
        }
    }
    
    /**
     * Gets create_index
     * @return int
     */
    public function getCreateIndex()
    {
        return $this->create_index;
    }
  
    /**
     * Sets create_index
     * @param int $create_index 
     * @return $this
     */
    public function setCreateIndex($create_index)
    {
        
        $this->create_index = $create_index;
        return $this;
    }
    
    /**
     * Gets id
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }
  
    /**
     * Sets id
     * @param string $id 
     * @return $this
     */
    public function setId($id)
    {
        
        $this->id = $id;
        return $this;
    }
    
    /**
     * Gets modify_index
     * @return int
     */
    public function getModifyIndex()
    {
        return $this->modify_index;
    }
  
    /**
     * Sets modify_index
     * @param int $modify_index 
     * @return $this
     */
    public function setModifyIndex($modify_index)
    {
        
        $this->modify_index = $modify_index;
        return $this;
    }
    
    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }
  
    /**
     * Sets name
     * @param string $name 
     * @return $this
     */
    public function setName($name)
    {
        
        $this->name = $name;
        return $this;
    }
    
    /**
     * Gets priority
     * @return int
     */
    public function getPriority()
    {
        return $this->priority;
    }
  
    /**
     * Sets priority
     * @param int $priority 
     * @return $this
     */
    public function setPriority($priority)
    {
        
        $this->priority = $priority;
        return $this;
    }
    
    /**
     * Gets status
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }
  
    /**
     * Sets status
     * @param string $status 
     * @return $this
     */
    public function setStatus($status)
    {
        
        $this->status = $status;
        return $this;
    }
    
    /**
     * Gets status_description
     * @return string
     */
    public function getStatusDescription()
    {
        return $this->status_description;
    }
  
    /**
     * Sets status_description
     * @param string $status_description 
     * @return $this
     */
    public function setStatusDescription($status_description)
    {
        
        $this->status_description = $status_description;
        return $this;
    }
    
    /**
     * Gets type
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }
  
    /**
     * Sets type
     * @param string $type 
     * @return $this
     */
    public function setType($type)
    {
        
        $this->type = $type;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Nomad\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Nomad\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
