<?php
/**
 * LogConfig
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nomad
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nomad\Model;

use \ArrayAccess;
/**
 * LogConfig Class Doc Comment
 *
 * @category    Class
 * @description The LogConfig object configures the log rotation policy for a task&#39;s stdout and stderr.
 * @package     Nomad
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LogConfig implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'max_files' => 'int',
        'max_file_size_mb' => 'int'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'max_files' => 'MaxFiles',
        'max_file_size_mb' => 'MaxFileSizeMB'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'max_files' => 'setMaxFiles',
        'max_file_size_mb' => 'setMaxFileSizeMb'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'max_files' => 'getMaxFiles',
        'max_file_size_mb' => 'getMaxFileSizeMb'
    );
  
    
    /**
      * $max_files 
      * @var int
      */
    protected $max_files;
    
    /**
      * $max_file_size_mb 
      * @var int
      */
    protected $max_file_size_mb;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->max_files = $data["max_files"];
            $this->max_file_size_mb = $data["max_file_size_mb"];
        }
    }
    
    /**
     * Gets max_files
     * @return int
     */
    public function getMaxFiles()
    {
        return $this->max_files;
    }
  
    /**
     * Sets max_files
     * @param int $max_files 
     * @return $this
     */
    public function setMaxFiles($max_files)
    {
        
        $this->max_files = $max_files;
        return $this;
    }
    
    /**
     * Gets max_file_size_mb
     * @return int
     */
    public function getMaxFileSizeMb()
    {
        return $this->max_file_size_mb;
    }
  
    /**
     * Sets max_file_size_mb
     * @param int $max_file_size_mb 
     * @return $this
     */
    public function setMaxFileSizeMb($max_file_size_mb)
    {
        
        $this->max_file_size_mb = $max_file_size_mb;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Nomad\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Nomad\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
