<?php
/**
 * ParameterizedJob
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nomad
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nomad\Model;

use \ArrayAccess;
/**
 * ParameterizedJob Class Doc Comment
 *
 * @category    Class
 * @description Specifies the job as a paramterized job such that it can be dispatched against.
 * @package     Nomad
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ParameterizedJob implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'meta_optional' => 'string[]',
        'meta_required' => 'string[]',
        'payload' => 'string'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'meta_optional' => 'MetaOptional',
        'meta_required' => 'MetaRequired',
        'payload' => 'Payload'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'meta_optional' => 'setMetaOptional',
        'meta_required' => 'setMetaRequired',
        'payload' => 'setPayload'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'meta_optional' => 'getMetaOptional',
        'meta_required' => 'getMetaRequired',
        'payload' => 'getPayload'
    );
  
    
    /**
      * $meta_optional 
      * @var string[]
      */
    protected $meta_optional;
    
    /**
      * $meta_required 
      * @var string[]
      */
    protected $meta_required;
    
    /**
      * $payload 
      * @var string
      */
    protected $payload;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->meta_optional = $data["meta_optional"];
            $this->meta_required = $data["meta_required"];
            $this->payload = $data["payload"];
        }
    }
    
    /**
     * Gets meta_optional
     * @return string[]
     */
    public function getMetaOptional()
    {
        return $this->meta_optional;
    }
  
    /**
     * Sets meta_optional
     * @param string[] $meta_optional 
     * @return $this
     */
    public function setMetaOptional($meta_optional)
    {
        
        $this->meta_optional = $meta_optional;
        return $this;
    }
    
    /**
     * Gets meta_required
     * @return string[]
     */
    public function getMetaRequired()
    {
        return $this->meta_required;
    }
  
    /**
     * Sets meta_required
     * @param string[] $meta_required 
     * @return $this
     */
    public function setMetaRequired($meta_required)
    {
        
        $this->meta_required = $meta_required;
        return $this;
    }
    
    /**
     * Gets payload
     * @return string
     */
    public function getPayload()
    {
        return $this->payload;
    }
  
    /**
     * Sets payload
     * @param string $payload 
     * @return $this
     */
    public function setPayload($payload)
    {
        $allowed_values = array("optional", "required", "forbidden");
        if (!in_array($payload, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'payload', must be one of 'optional', 'required', 'forbidden'");
        }
        $this->payload = $payload;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Nomad\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Nomad\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
