<?php
/**
 * RestartPolicy
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nomad
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Nomad\Model;

use \ArrayAccess;
/**
 * RestartPolicy Class Doc Comment
 *
 * @category    Class
 * @description Model for RestartPolicy
 * @package     Nomad
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RestartPolicy implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'attempts' => 'int',
        'delay' => 'int',
        'interval' => 'int',
        'mode' => 'string'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'attempts' => 'Attempts',
        'delay' => 'Delay',
        'interval' => 'Interval',
        'mode' => 'Mode'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'attempts' => 'setAttempts',
        'delay' => 'setDelay',
        'interval' => 'setInterval',
        'mode' => 'setMode'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'attempts' => 'getAttempts',
        'delay' => 'getDelay',
        'interval' => 'getInterval',
        'mode' => 'getMode'
    );
  
    
    /**
      * $attempts 
      * @var int
      */
    protected $attempts;
    
    /**
      * $delay 
      * @var int
      */
    protected $delay;
    
    /**
      * $interval 
      * @var int
      */
    protected $interval;
    
    /**
      * $mode 
      * @var string
      */
    protected $mode;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->attempts = $data["attempts"];
            $this->delay = $data["delay"];
            $this->interval = $data["interval"];
            $this->mode = $data["mode"];
        }
    }
    
    /**
     * Gets attempts
     * @return int
     */
    public function getAttempts()
    {
        return $this->attempts;
    }
  
    /**
     * Sets attempts
     * @param int $attempts 
     * @return $this
     */
    public function setAttempts($attempts)
    {
        
        $this->attempts = $attempts;
        return $this;
    }
    
    /**
     * Gets delay
     * @return int
     */
    public function getDelay()
    {
        return $this->delay;
    }
  
    /**
     * Sets delay
     * @param int $delay 
     * @return $this
     */
    public function setDelay($delay)
    {
        
        $this->delay = $delay;
        return $this;
    }
    
    /**
     * Gets interval
     * @return int
     */
    public function getInterval()
    {
        return $this->interval;
    }
  
    /**
     * Sets interval
     * @param int $interval 
     * @return $this
     */
    public function setInterval($interval)
    {
        
        $this->interval = $interval;
        return $this;
    }
    
    /**
     * Gets mode
     * @return string
     */
    public function getMode()
    {
        return $this->mode;
    }
  
    /**
     * Sets mode
     * @param string $mode 
     * @return $this
     */
    public function setMode($mode)
    {
        
        $this->mode = $mode;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Nomad\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Nomad\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
