<?php
/**
 * JobApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Nomad
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace Nomad\Api;

use \Nomad\Configuration;
use \Nomad\ApiClient;
use \Nomad\ApiException;
use \Nomad\ObjectSerializer;

/**
 * JobApiTest Class Doc Comment
 *
 * @category Class
 * @package  Nomad
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class JobApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for create
     *
     * 
     *
     */
    public function test_create() {

    }
    
    /**
     * Test case for get
     *
     * 
     *
     */
    public function test_get() {

    }
    
    /**
     * Test case for update
     *
     * 
     *
     */
    public function test_update() {

    }
    
    /**
     * Test case for remove
     *
     * 
     *
     */
    public function test_remove() {

    }
    
    /**
     * Test case for getAllocations
     *
     * 
     *
     */
    public function test_getAllocations() {

    }
    
    /**
     * Test case for dispatch
     *
     * 
     *
     */
    public function test_dispatch() {

    }
    
    /**
     * Test case for createEvaluation
     *
     * 
     *
     */
    public function test_createEvaluation() {

    }
    
    /**
     * Test case for getEvaluations
     *
     * 
     *
     */
    public function test_getEvaluations() {

    }
    
    /**
     * Test case for forcePeriodic
     *
     * 
     *
     */
    public function test_forcePeriodic() {

    }
    
    /**
     * Test case for getSummary
     *
     * 
     *
     */
    public function test_getSummary() {

    }
    
}
